[package]
name = "xwt-cert-gen"
version = "0.2.1"
edition = "2021"
resolver = "2"
license = "MIT"
description = """
Certificate generation factilities, provided by and for xwt.
Useful for generating certificate. Also usable without xwt.
"""
repository = "https://github.com/MOZGIII/xwt"

[package.metadata.cargo-shear]
ignored = ["sha2", "p256", "spki", "rand", "getrandom"]

[dependencies]
der = { workspace = true }
getrandom = { workspace = true }
sha2 = { workspace = true, features = ["oid"] }
signature = { workspace = true }
spki = { workspace = true }
thiserror = { workspace = true }
x509-cert = { workspace = true }

[dev-dependencies]
p256 = { version = "0.13", features = ["ecdsa"] }
rand = { workspace = true }
