[package]
name = "xwt-web"
version = "0.20.0"
edition = "2021"
resolver = "2"
license = "MIT"
description = """
An implementation of the xwt that runs in the browser.
Powered by wasm-bindgen and web-sys.
"""
repository = "https://github.com/MOZGIII/xwt"

[package.metadata.docs.rs]
default-target = "wasm32-unknown-unknown"

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys-async-io = { workspace = true }
web-sys-stream-utils = { workspace = true }
web-wt-sys = { workspace = true }
xwt-core = { workspace = true }

js-sys = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["ReadableStream", "WritableStream", "DomException"] }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
xwt-cert-fingerprint = { workspace = true }
xwt-test-assets = { workspace = true }
xwt-tests = { workspace = true }

static_assertions = { workspace = true }
tracing-wasm = { workspace = true }
wasm-bindgen-test = { workspace = true }
web-sys = { workspace = true, features = ["console"] }
