[package]
name = "xwt-wtransport"
version = "0.19.0"
edition = "2021"
resolver = "2"
license = "MIT"
description = """
An implementation of the xwt that runs natively via wtransport crate.
"""
repository = "https://github.com/MOZGIII/xwt"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
xwt-core = { workspace = true, features = ["std"] }

thiserror = { workspace = true }
tokio = { workspace = true, default-features = false, optional = true }
wtransport = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
xwt-cert-fingerprint = { workspace = true }
xwt-test-assets = { workspace = true }
xwt-tests = { workspace = true }

color-eyre = { workspace = true }
static_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["tokio", "wtransport/ring"]
