[package]
name = "xwt-erased"
version = "0.6.0"
edition = "2021"
resolver = "2"
rust-version = "1.81"
license = "MIT"
description = """
Type-erased wrappers for the `xwt-dyn` traits.
"""
repository = "https://github.com/MOZGIII/xwt"

[dependencies]
xwt-core = { workspace = true, optional = true }
xwt-dyn = { workspace = true }

static_assertions = { workspace = true, optional = true }
tracing = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
tracing = { workspace = true }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
xwt-web = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
xwt-wtransport = { workspace = true }

wtransport = { workspace = true }

[features]
default = ["core-compat"]

core-compat = ["dep:xwt-core", "dep:static_assertions"]
trace-calls = ["dep:tracing"]
