[package]
name = "xwt-example-client-web"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.cargo-shear]
ignored = ["getrandom"]

[target.'cfg(target_family = "wasm")'.dependencies]
# Shared code between native and web examples.
xwt-example-client-shared = { path = "../client-shared", default-features = false }

# Core xwt primitives and driver.
xwt-cert-fingerprint = { workspace = true }
xwt-core = { workspace = true }
xwt-web = { workspace = true }

# The dependency specific to this being an xwt example that is designed to
# work with an xwt test server.
xwt-test-assets = { workspace = true }

# The rest of the dependencies.
getrandom = { workspace = true }
rand = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "HtmlElement"] }
