[package]
name = "xwt-erased-example-server-shared"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
xwt-erased = { path = "../../../crates/xwt-erased" }

futures-util = "0.3"
tokio = { version = "1", default-features = false, features = ["time"] }
