[package]
name = "xwt-test-server"
version = "0.7.5"
edition = "2021"
resolver = "2"
license = "MIT"
description = """
The server to use for xwt testing.
Not intended to be wasm-compatible.
"""
repository = "https://github.com/MOZGIII/xwt"
autobins = false

[[bin]]
name = "xwt-test-server"
path = "src/main.rs"
required-features = ["bin"]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
xwt-cert-fingerprint = { workspace = true }
xwt-test-assets = { workspace = true }

color-eyre = { workspace = true, optional = true }
envfury = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
typle = { workspace = true }
wtransport = { workspace = true }

[features]
bin = ["dep:color-eyre", "dep:envfury", "dep:tracing-subscriber", "tokio/macros", "wtransport/ring"]
default = ["bin"]
