[package]
name = "xwt-erased-example-client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1"

xwt-erased-example-client-shared = { version = "0.1", path = "../client-shared", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen-futures = "0.4"
xwt-erased-example-client-web = { version = "0.1", path = "../client-web", default-features = false }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
xwt-erased-example-client-native = { version = "0.1", path = "../client-native", default-features = false }
