[package]
name = "xwt-example-client-native"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.cargo-shear]
ignored = ["tokio"]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# Shared code between native and web examples.
xwt-example-client-shared = { path = "../client-shared", default-features = false }

# Core xwt primitives and driver.
xwt-cert-fingerprint = { workspace = true }
xwt-core = { workspace = true }
xwt-wtransport = { workspace = true }

# The dependency specific to this being an xwt example that is designed to
# work with an xwt test server.
xwt-test-assets = { workspace = true }

# The rest of the dependencies.
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wtransport = { workspace = true, features = ["ring"] }
