[package]
name = "xwt-erased-example-client-native"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# Shared code between native and web examples.
xwt-erased-example-client-shared = { path = "../client-shared", default-features = false }

# Core xwt primitives and driver.
xwt-cert-fingerprint = { path = "../../../crates/xwt-cert-fingerprint", default-features = false }
xwt-erased = { path = "../../../crates/xwt-erased", default-features = false }
xwt-wtransport = { path = "../../../crates/xwt-wtransport", default-features = false }

# The dependency specific to this being an xwt example that is designed to
# work with an xwt test server.
xwt-test-assets = { path = "../../../crates/xwt-test-assets", default-features = false }

# The rest of the dependencies.
rand = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wtransport = { version = "0.6", features = ["self-signed"] }
